import type { Metadata } from "next";
import { Download, FileStack, Info } from "lucide-react";
import { PageContainer, PageHeader } from "@/components/common/page-header";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getNavItem } from "@/config/navigation";
import { DOCUMENT_TEMPLATES } from "@/config/templates";
import { getT } from "@/lib/i18n/server";

export async function generateMetadata(): Promise<Metadata> {
  const t = await getT();
  return { title: t(getNavItem("templates").label) };
}

export default async function TemplatesPage() {
  const t = await getT();

  return (
    <PageContainer>
      <PageHeader
        icon={FileStack}
        title={t(getNavItem("templates").label)}
        description={t(
          "แม่แบบ .docx ที่ระบบใช้สร้างเอกสาร — ตัวแปรใช้ {tag} ลูปใช้ {#items}…{/items}",
          "The .docx templates the system uses to generate documents — variables use {tag}, loops use {#items}…{/items}",
        )}
        className="mb-5"
      />

      <div className="flex flex-col gap-4">
        {DOCUMENT_TEMPLATES.map((template) => (
          <Card key={template.file}>
            <CardHeader>
              <div>
                <CardTitle className="flex items-center gap-2">
                  {t(template.name)} <Badge tone="brand">{template.version}</Badge>
                </CardTitle>
                <CardDescription>{t(template.description)}</CardDescription>
              </div>
              <a href={`/api/templates/${template.file}`} className={buttonVariants({ variant: "secondary" })} download>
                <Download aria-hidden /> {t("ดาวน์โหลดแม่แบบ", "Download template")}
              </a>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto rounded-[var(--radius-control)] border border-border scrollbar-thin">
                <table className="w-full min-w-[520px] text-left text-[13px]">
                  <thead className="sticky top-0 bg-neutral-50 text-xs text-neutral-500">
                    <tr className="h-[var(--spacing-row)]">
                      <th scope="col" className="px-3 font-medium">{t("ตัวแปร", "Variable")}</th>
                      <th scope="col" className="px-3 font-medium">{t("ความหมาย", "Description")}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {template.variables.map((v) => (
                      <tr key={v.tag} className="h-[var(--spacing-row)] border-t border-border hover:bg-row-hover">
                        <td className="px-3 font-mono text-xs text-brand-800">{v.tag}</td>
                        <td className="px-3 text-neutral-700">{t(v.description)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="mt-3 flex items-start gap-2 text-xs text-muted-foreground">
                <Info className="mt-0.5 size-3.5 shrink-0" aria-hidden />
                {t("แม่แบบนี้สร้างจากสคริปต์", "This template is generated by the script")} <code className="font-mono">npm run template:invitation</code>{" "}
                {t(
                  "ใช้ถ้อยคำตามหนังสือต้นฉบับของคณะทุกตัวอักษร — การอัปโหลดแม่แบบใหม่พร้อมเก็บเวอร์ชันบน Supabase Storage จะเปิดใช้เมื่อเชื่อมฐานข้อมูล (Phase 1)",
                  "and follows the wording of the faculty's original letter exactly — uploading new templates with version history on Supabase Storage will be enabled once the database is connected (Phase 1)",
                )}
              </p>
            </CardContent>
          </Card>
        ))}
      </div>
    </PageContainer>
  );
}
